In [1]:
import numpy as np

SplitLine = "\n==============================\n"

def ArrayAttr(x):
    print(f"维度数(秩)：{x.ndim}; 元素类型：{x.dtype}; 数组的维度形状：{x.shape}; 元素个数：{x.size}; 元素的字节大小：{x.itemsize}", end=SplitLine)

In [2]:
lst_a = [1, 2, 3, 4]
a = np.asarray_chkfinite(lst_a)
print(type(a))
b= np.array(lst_a)
print(type(b))

x = np.arange(10)
print(x)
x = np.arange(1, 13, 2)
print(x)
# 构建在此范围内需要的n个数据。等差数列
x = np.linspace(1, 8, 3)
print(x)
# 构建在此范围内需要的n个数据。等比数列, 起始值=base^start，结束值=base^stop
x = np.logspace(1, 8, 8, base=2)
print(x, end=SplitLine)
x = np.zeros((2, 3, 4), dtype=float)
print(x.shape, end=SplitLine)
x = np.ones([2, 3, 4], dtype=float)
print(x, end=SplitLine)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11]
[1.  4.5 8. ]
[  2.   4.   8.  16.  32.  64. 128. 256.]
(2, 3, 4)
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
