In [1]:
import numpy as np

SplitLine = "\n==============================\n"

def PrintArray(info:str, x):
    print(info + ":\n", x)
    print(f"维度数(秩)：{x.ndim}; 元素类型：{x.dtype}; 数组的维度形状：{x.shape}; 元素个数：{x.size}; 元素的字节大小：{x.itemsize}", end=SplitLine)

In [2]:
a = np.random.randint(1, 50, size=(3, 4))
PrintArray("a", a)

a:
 [[20  5  8 42]
 [ 9 22 21  3]
 [48 38 23 33]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8


* numpy.sort() 函数返回输入数组的排序副本

In [7]:
b = np.sort(a)
PrintArray("b", b)

b0 = np.sort(a, axis=0)
PrintArray("b0", b0)

dt = np.dtype([('name',  'S10'),('age',  int)]) 
p = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt) 
PrintArray("p", p)
bp0 = np.sort(p, order="name")
PrintArray("bp0", bp0)

# 无降序选项，可通过切片操作进行转换
b1 = np.sort(a, axis=1)
PrintArray("b1", b1)
b1_inv = b1[:, ::-1]
PrintArray("b1_inv", b1_inv)

b:
 [[ 5  8 20 42]
 [ 3  9 21 22]
 [23 33 38 48]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
b0:
 [[ 9  5  8  3]
 [20 22 21 33]
 [48 38 23 42]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
p:
 [(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
维度数(秩)：1; 元素类型：[('name', 'S10'), ('age', '<i8')]; 数组的维度形状：(4,); 元素个数：4; 元素的字节大小：18
bp0:
 [(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]
维度数(秩)：1; 元素类型：[('name', 'S10'), ('age', '<i8')]; 数组的维度形状：(4,); 元素个数：4; 元素的字节大小：18
b1:
 [[ 5  8 20 42]
 [ 3  9 21 22]
 [23 33 38 48]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
b1_inv:
 [[42 20  8  5]
 [22 21  9  3]
 [48 38 33 23]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8


* numpy.argsort() 函数返回的是数组值从小到大的索引值。

In [22]:
PrintArray("a", a)

# 并不会将a进行修改
b = np.argsort(a)
PrintArray("b", b)

b0 = np.argsort(a, axis=0)
PrintArray("b0", b0)
b1 = np.argsort(a, axis=1)
PrintArray("b1", b1)

PrintArray("a", a)

sorted_a = np.empty_like(a)
# 使用循环重新排序
for xarr, iarr, dsarr in zip(a, b, sorted_a):
    for i in range(len(xarr)):
        dsarr[i] = xarr[iarr[i]]
PrintArray("sorted_a", sorted_a)

a:
 [[20  5  8 42]
 [ 9 22 21  3]
 [48 38 23 33]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
b:
 [[1 2 0 3]
 [3 0 2 1]
 [2 3 1 0]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
b0:
 [[1 0 0 1]
 [0 1 1 2]
 [2 2 2 0]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
b1:
 [[1 2 0 3]
 [3 0 2 1]
 [2 3 1 0]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
a:
 [[20  5  8 42]
 [ 9 22 21  3]
 [48 38 23 33]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
sorted_a:
 [[ 5  8 20 42]
 [ 3  9 21 22]
 [23 33 38 48]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8


* numpy.argmax() 和 numpy.argmin()函数分别沿给定轴返回最大和最小元素的索引。

In [24]:
PrintArray("a", a)

b_imin = np.argmin(a)
PrintArray("b_imin", b_imin)
b_imin0 = np.argmin(a, axis=0)
PrintArray("b_imin0", b_imin0)
b_imin1 = np.argmin(a, axis=1)
PrintArray("b_imin1", b_imin1)

b_imax = np.argmax(a)
PrintArray("b_imax", b_imax)
b_imax0 = np.argmax(a, axis=0)
PrintArray("b_imax0", b_imax0)
b_imax1 = np.argmax(a, axis=1)
PrintArray("b_imax1", b_imax1)

a:
 [[20  5  8 42]
 [ 9 22 21  3]
 [48 38 23 33]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
b_imin:
 7
维度数(秩)：0; 元素类型：int64; 数组的维度形状：(); 元素个数：1; 元素的字节大小：8
b_imin0:
 [1 0 0 1]
维度数(秩)：1; 元素类型：int64; 数组的维度形状：(4,); 元素个数：4; 元素的字节大小：8
b_imin1:
 [1 3 2]
维度数(秩)：1; 元素类型：int64; 数组的维度形状：(3,); 元素个数：3; 元素的字节大小：8
b_imax:
 8
维度数(秩)：0; 元素类型：int64; 数组的维度形状：(); 元素个数：1; 元素的字节大小：8
b_imax0:
 [2 2 2 0]
维度数(秩)：1; 元素类型：int64; 数组的维度形状：(4,); 元素个数：4; 元素的字节大小：8
b_imax1:
 [3 1 0]
维度数(秩)：1; 元素类型：int64; 数组的维度形状：(3,); 元素个数：3; 元素的字节大小：8


* numpy.nonzero() 函数返回输入数组中非零元素的索引。

In [31]:
ae = np.eye(3, 4)
PrintArray("ae", ae)

ae_nzi = np.nonzero(ae)
print("ae_nzi:\n", ae_nzi)

# 获取非零元素
ae_nz = ae[ae_nzi]
PrintArray("ae_nz", ae_nz)

ax0, ax1 = ae_nzi
for i, j in zip(ax0, ax1):
    print(f"({i}, {j}): ", ae[i][j])

ae:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
维度数(秩)：2; 元素类型：float64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
ae_nzi:
 (array([0, 1, 2]), array([0, 1, 2]))
ae_nz:
 [1. 1. 1.]
维度数(秩)：1; 元素类型：float64; 数组的维度形状：(3,); 元素个数：3; 元素的字节大小：8
(0, 0):  1.0
(1, 1):  1.0
(2, 2):  1.0


* numpy.where() 函数返回输入数组中满足给定条件的元素的索引。

In [41]:
PrintArray("a", a)

b25 = np.where(a > 25)
print("b25: ", b25)

b = a[b25]
PrintArray("b", b)

# 满足条件的执行 “a/2”， 不满足条件的执行“2*a”
b25_0 = np.where(a > 25, a/2, 2*a)
PrintArray("b25_0", b25_0)

# 比较x，y两个数组大小，当对应位置x中的元素大于y中的元素，则取x中的元素，反之取y中的元素
x = np.random.randint(1, 30, size=(3, 4))
y = np.random.randint(10, 40, size=(3, 4))
PrintArray("x", x)
PrintArray("y", y)
x_y = np.where(x > y, x, y)
PrintArray("x_y", x_y)

a:
 [[20  5  8 42]
 [ 9 22 21  3]
 [48 38 23 33]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
b25:  (array([0, 2, 2, 2]), array([3, 0, 1, 3]))
b:
 [42 48 38 33]
维度数(秩)：1; 元素类型：int64; 数组的维度形状：(4,); 元素个数：4; 元素的字节大小：8
b25_0:
 [[40.  10.  16.  21. ]
 [18.  44.  42.   6. ]
 [24.  19.  46.  16.5]]
维度数(秩)：2; 元素类型：float64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
x:
 [[13 28 11 21]
 [10 22 16 10]
 [ 6 25 13 26]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
y:
 [[12 18 22 36]
 [14 33 24 31]
 [23 14 23 11]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
x_y:
 [[13 28 22 36]
 [14 33 24 31]
 [23 25 23 26]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8


* numpy.extract() 函数根据某个条件从数组中抽取元素，返回满条件的元素。

In [44]:
PrintArray("a", a)

cond = np.mod(a, 2) == 0
PrintArray("cond", cond)

a_even = np.extract(cond, a)
PrintArray("a_even", a_even)
# 等价
a_even_ = a[cond]
PrintArray("a_even_", a_even_)

a:
 [[20  5  8 42]
 [ 9 22 21  3]
 [48 38 23 33]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
cond:
 [[ True False  True  True]
 [False  True False False]
 [ True  True False False]]
维度数(秩)：2; 元素类型：bool; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：1
a_even:
 [20  8 42 22 48 38]
维度数(秩)：1; 元素类型：int64; 数组的维度形状：(6,); 元素个数：6; 元素的字节大小：8
a_even_:
 [20  8 42 22 48 38]
维度数(秩)：1; 元素类型：int64; 数组的维度形状：(6,); 元素个数：6; 元素的字节大小：8
