In [1]:
import numpy as np

SplitLine = "\n==============================\n"

def ArrayAttr(x):
    print(f"维度数(秩)：{x.ndim}; 元素类型：{x.dtype}; 数组的维度形状：{x.shape}; 元素个数：{x.size}; 元素的字节大小：{x.itemsize}", end=SplitLine)

In [2]:
# 数组迭代
a = np.arange(12).reshape(3, 4)
print(a)
ArrayAttr(a)

print("使用 nditer:")
for x in np.nditer(a):
    print(x, end=",")
print("\n", end=SplitLine)

aT = a.T
print("aT:\n", aT)
ArrayAttr(aT)
for x in np.nditer(aT):
    print(x, end=",")
print("\n", end=SplitLine)

aT1 = a.T.copy()
print("aT1(copy):\n", aT1)
ArrayAttr(aT1)
for x in np.nditer(aT1):
    print(x, end=",")
print("\n", end=SplitLine)

print("aT C style iter:\n")
for x in np.nditer(aT, order='C'):
    print(x, end=",")
print("\n", end=SplitLine)

print("修改数组中元素的值", end=SplitLine)
for x in np.nditer(a, op_flags=["readwrite"]):
    x[...] = 2 * x  # x[...]是修改原numpy元素，x只是个拷贝
print(a)

print("使用外部循环")
for x in np.nditer(a, flags=["external_loop"], order="F"):
    print(x, end=",")
print("\n", end=SplitLine)
for x in np.nditer(a, flags=["external_loop"], order="C"):
    print(x, end=",")
print("\n", end=SplitLine)

print("广播迭代，迭代多个数组")
b = np.array([1, 3, 5, 7]).reshape((1, 4))
print(b)
ArrayAttr(b)
for x, y in np.nditer([a, b]):
    print(f"{x} : {y}", end=", ")
print("\n", end=SplitLine)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
使用 nditer:
0,1,2,3,4,5,6,7,8,9,10,11,

aT:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(4, 3); 元素个数：12; 元素的字节大小：8
0,1,2,3,4,5,6,7,8,9,10,11,

aT1(copy):
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(4, 3); 元素个数：12; 元素的字节大小：8
0,4,8,1,5,9,2,6,10,3,7,11,

aT C style iter:

0,4,8,1,5,9,2,6,10,3,7,11,

修改数组中元素的值
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
使用外部循环
[ 0  8 16],[ 2 10 18],[ 4 12 20],[ 6 14 22],

[ 0  2  4  6  8 10 12 14 16 18 20 22],

广播迭代，迭代多个数组
[[1 3 5 7]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(1, 4); 元素个数：4; 元素的字节大小：8
0 : 1, 2 : 3, 4 : 5, 6 : 7, 8 : 1, 10 : 3, 12 : 5, 14 : 7, 16 : 1, 18 : 3, 20 : 5, 22 : 7, 

