In [1]:
import numpy as np

SplitLine = "\n==============================\n"

def ArrayAttr(x):
    print(f"维度数(秩)：{x.ndim}; 元素类型：{x.dtype}; 数组的维度形状：{x.shape}; 元素个数：{x.size}; 元素的字节大小：{x.itemsize}", end=SplitLine)

In [2]:
x = np.arange(1, 13)
print(x, end=SplitLine)
ArrayAttr(x)
s = x[2:8:2]
print(s, end=SplitLine)
s = x[5:]
print(s, end=SplitLine)
s = x[:5]
print(s, end=SplitLine)
# 切片索引
x = np.arange(1, 65).reshape((4, 4, 4))
print(x, end=SplitLine)
ArrayAttr(x)
s = x[1:4:2]  # 只在第1个维度上起作用
print(s)
ArrayAttr(s)

s = x[:, 1:4:2]  # 只在第2个维度上起作用
print(s)
ArrayAttr(s)
s1 = x[..., 1:4:2]  # 在最后维度上起作用，省略号为自动计算的维度，且只能有一个省略号
print(s1)
ArrayAttr(s1)
s1 = x[..., 1:4:2, :]  # 在第2维度上起作用
print(s1)
ArrayAttr(s1)

s = x[:,:,1:4:2]  # 只在第3个维度上起作用
print(s)
ArrayAttr(s)

s = x[:,:2,:]
print(s)
ArrayAttr(s)
s = x[:,2:,:]
print(s)
ArrayAttr(s)
# 布尔条件选择
s = x[x > 32]
print(s)
ArrayAttr(s)
s = x[~(x > 32)]
print(s)
ArrayAttr(s)
# 花式索引，注意返回数组的维度
s = x[[0, 3]]
print(s)
ArrayAttr(s)
s = x[[0, 3], [1, 2]]
print(s)
ArrayAttr(s)
s = x[[0, 3], [1, 2], [2, 3]]  # 相当于返回点(0,1,2)和点(3，2，3)的值,这里只能使用"[]",不能使用"()"
print(s)
ArrayAttr(s)
s = x[(0, 3), (1, 2), (2, 3)]  # 相当于返回点(0,1,2)和点(3，2，3)的值
print(s)
ArrayAttr(s)

# 使用"[]"与使用"()"区别
s = x[[0, 3]]
print(s)
ArrayAttr(s)
s = x[(0, 3)]
print(s)
ArrayAttr(s)
s = x[(0, 3),]
print(s)
ArrayAttr(s)

# 不同维度使用不同的索引数组
s = x[[0, 3]][:,[1, 2]][:,:,[2, 3]]
print(s)
ArrayAttr(s)

s = x[np.ix_([0, 3], [1, 2])]
print(s)
ArrayAttr(s)
s = x[np.ix_([0, 3], [1, 2], [2, 3])]
print(s)
ArrayAttr(s)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
维度数(秩)：1; 元素类型：int64; 数组的维度形状：(12,); 元素个数：12; 元素的字节大小：8
[3 5 7]
[ 6  7  8  9 10 11 12]
[1 2 3 4 5]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]
维度数(秩)：3; 元素类型：int64; 数组的维度形状：(4, 4, 4); 元素个数：64; 元素的字节大小：8
[[[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]
维度数(秩)：3; 元素类型：int64; 数组的维度形状：(2, 4, 4); 元素个数：32; 元素的字节大小：8
[[[ 5  6  7  8]
  [13 14 15 16]]

 [[21 22 23 24]
  [29 30 31 32]]

 [[37 38 39 40]
  [45 46 47 48]]

 [[53 54 55 56]
  [61 62 63 64]]]
维度数(秩)：3; 元素类型：int64; 数组的维度形状：(4, 2, 4); 元素个数：32; 元素的字节大小：8
[[[ 2  4]
  [ 6  8]
  [10 12]
  [14 16]]

 [[18 20]
  [22 24]
  [26 28]
  [30 32]]

 [[34 36]
  [38 40]
  [42 44]
  [46 48]]

 [[50 52]
  [54 56]
  [58