In [1]:
import numpy as np

SplitLine = "\n==============================\n"

def ArrayAttr(x):
    print(f"维度数(秩)：{x.ndim}; 元素类型：{x.dtype}; 数组的维度形状：{x.shape}; 元素个数：{x.size}; 元素的字节大小：{x.itemsize}", end=SplitLine)

In [2]:
# 广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式， 对数组的算术运算通常在相应的元素上进行。
a = np.arange(1, 13)
b = np.linspace(1, 12, 12)
print("a:\n", a, end=SplitLine)
print("b:\n", b, end=SplitLine)
c = a * b
print(c, end=SplitLine)
c = a.dot(b)
print(c, end=SplitLine)

# 在dim=2上的元素进行计算
a = a.reshape(3, 2, 2)
print(a)
ArrayAttr(a)
print("在dim=2上的元素进行计算", end=SplitLine)
x = np.array([2, 4])
print(x)
ArrayAttr(x)
y = a + x
print(y)
ArrayAttr(y)
y = a * x
print(y)
ArrayAttr(y)
# 效果相当于：
# x = np.tile(x, (3, 2, 1))  # 将原矩阵横向、纵向地复制
# print(x)
# ArrayAttr(x)

# 在dim=1上的元素进行计算
print("在dim=1上的元素进行计算", end=SplitLine)
# a = a.reshape(3, 2, 2)
print(a)
ArrayAttr(a)    
x = np.array([2, 4]).reshape(2, 1)
print(x)
ArrayAttr(x)
y = a + x
print(y)
ArrayAttr(y)
y = a * x
print(y)
ArrayAttr(y)
# 效果相当于：
# x = np.tile(x, (3, 1, 2))
# print(x)
# ArrayAttr(x)

# 在dim=0上的元素进行计算
print("在dim=0上的元素进行计算", end=SplitLine)
print(a)
ArrayAttr(a)
x = np.array([2, 4, 6]).reshape( 3, 1, 1)
print(x)
ArrayAttr(x)
y = a + x
print(y)
ArrayAttr(y)
y = a * x
print(y)
ArrayAttr(y)
# 效果相当于：
# x = np.tile(x, (1, 2, 2))
# print(x)
# ArrayAttr(x)

a:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
b:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121. 144.]
650.0
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
维度数(秩)：3; 元素类型：int64; 数组的维度形状：(3, 2, 2); 元素个数：12; 元素的字节大小：8
在dim=2上的元素进行计算
[2 4]
维度数(秩)：1; 元素类型：int64; 数组的维度形状：(2,); 元素个数：2; 元素的字节大小：8
[[[ 3  6]
  [ 5  8]]

 [[ 7 10]
  [ 9 12]]

 [[11 14]
  [13 16]]]
维度数(秩)：3; 元素类型：int64; 数组的维度形状：(3, 2, 2); 元素个数：12; 元素的字节大小：8
[[[ 2  8]
  [ 6 16]]

 [[10 24]
  [14 32]]

 [[18 40]
  [22 48]]]
维度数(秩)：3; 元素类型：int64; 数组的维度形状：(3, 2, 2); 元素个数：12; 元素的字节大小：8
在dim=1上的元素进行计算
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
维度数(秩)：3; 元素类型：int64; 数组的维度形状：(3, 2, 2); 元素个数：12; 元素的字节大小：8
[[2]
 [4]]
维度数(秩)：2; 元素类型：int64; 数组的维度形状：(2, 1); 元素个数：2; 元素的字节大小：8
[[[ 3  4]
  [ 7  8]]

 [[ 7  8]
  [11 12]]

 [[11 12]
  [15 16]]]
维度数(秩)：3; 元素类型：int64; 数组的维度形状：(3, 2, 2); 元素个数：12; 元素的字节大小：8
[[[ 2  4]
  [12 16]]

 [[10 12]
  [28 32]]

 [[18